version: '3.8'

services:
  posts:
    restart: always
    build:
      context: .
      dockerfile: ./apps/posts/Dockerfile
    env_file:
      - ./apps/posts/.env
    ports:
      - '3001:3001'
    volumes:
      - ./apps/posts:/usr/src/app/apps/posts
      - ./libs/common:/usr/src/app/libs/common

  auth:
    restart: always
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3002:3002'
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth
      - ./libs/common:/usr/src/app/libs/common

  payments:
    restart: always
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
    volumes:
      - ./apps/payments:/usr/src/app/apps/payments
      - ./libs/common:/usr/src/app/libs/common

  chat:
    restart: always
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
    command: npm run start:dev chat
    env_file:
      - ./apps/chat/.env
    ports:
      - '3004:3004'
    volumes:
      - ./apps/chat:/usr/src/app/apps/chat
      - ./libs/common:/usr/src/app/libs/common


  gateway:
    restart: always
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3000:3000'
    volumes:
      - ./apps/gateway:/usr/src/app/apps/gateway
      - ./libs/common:/usr/src/app/libs/common

  mongo:
    image: mongo